debug: false
patch-villagers-on-chunk-loading: true
# 失智棒 工具属性

item:
  type: GLASS_BOTTLE
  name: "&r失智之瓶"
  lore: |
    &7由椰术制成, 能够抽取村民智力的瓶子
    &7拿起它对村民使用, 村民就失去智力
    &7甚至还能恢复回来...
    &7
    &b由于高版本村民AI优化极差
    &b建议您关闭聚集村民的AI避免卡服
    &7
    &7右键调整村民AI
    &7左键来查看村民状态
    &8(道具)
# 提示信息
message:
  apply: "&7对村民使用了失智之瓶，村民变得迟钝起来..."
  undo: "&7对村民使用了失智之瓶，村民恢复了智力..."
  query-miss: "&2[√] &7这个村民看起来一切正常."
  query-hit: "&4[×] &7这个村民看起来失了智."
# 补货时刻表 （tick）
restock-schedule:
  - 3000
  - 5000
  - 6000
jobsite-max-distance: 2