name: VillagerAIHelper
version: '${project.version}'
main: com.ghostchu.villageraihelper.VillagerAIHelper
api-version: 1.16
description: Villager AI Helper
commands:
  villageraihelper:
    usage: /villageraihelper <give/stats>
    description: Main Command